from src.edit_candidates import classify_edit_candidates
from src.reviewer import Finding
from src.verifier import VerificationResult


def _finding(
    *,
    action="EDIT",
    existing="text",
    replacement="new",
    anchor=None,
    insert_position=None,
    verdict="CONFIRMED",
    correction=None,
):
    # Chunk 7: action-specific fields must satisfy the parse-time
    # validator or the finding's edit proposal is rejected. Default the
    # ADD shape to ``anchor="anchor para"`` / ``insert_position="after"``
    # so legacy tests that just say ``action="ADD"`` keep producing a
    # valid edit proposal; tests that need an invalid ADD pass
    # ``anchor=None`` explicitly.
    if action == "ADD" and anchor is None and insert_position is None:
        anchor = "anchor paragraph text"
        insert_position = "after"
    f = Finding(
        severity="HIGH",
        fileName="spec.docx",
        section="2.1",
        issue="Issue",
        actionType=action,
        existingText=existing,
        replacementText=replacement,
        codeReference="CBC",
        confidence=0.9,
        anchorText=anchor,
        insertPosition=insert_position,
    )
    if verdict is not None:
        f.verification = VerificationResult(verdict=verdict, explanation="", sources=[], correction=correction)
    return f


def test_confirmed_edit_defaults_selected():
    candidates = classify_edit_candidates([_finding(verdict="CONFIRMED")])

    assert len(candidates) == 1
    c = candidates[0]
    assert c.eligible is True
    assert c.default_selected is True
    assert c.verdict_badge == "CONFIRMED"


def test_corrected_uses_correction_replacement_text():
    candidates = classify_edit_candidates([_finding(verdict="CORRECTED", replacement="old", correction="better")])

    assert len(candidates) == 1
    c = candidates[0]
    assert c.default_selected is True
    assert c.verdict_badge == "CORRECTED"
    assert c.replacement_text == "better"


def test_unverified_included_unchecked_by_default():
    candidates = classify_edit_candidates([_finding(verdict="UNVERIFIED")])

    assert len(candidates) == 1
    c = candidates[0]
    assert c.default_selected is False
    assert c.verdict_badge == "UNVERIFIED"


def test_disputed_marked_ineligible_with_reason():
    candidates = classify_edit_candidates([_finding(verdict="DISPUTED")])

    assert len(candidates) == 1
    c = candidates[0]
    assert c.eligible is False
    assert c.default_selected is False
    assert c.ineligible_reason == "Finding was disputed by the verifier"
    assert c.verdict_badge == "DISPUTED"


def test_add_action_included_and_eligible_when_verified():
    candidates = classify_edit_candidates([_finding(action="ADD", verdict="CONFIRMED")])

    assert len(candidates) == 1
    c = candidates[0]
    assert c.action_type == "ADD"
    assert c.eligible is True
    assert c.default_selected is True
    assert c.ineligible_reason is None


def test_none_verification_marked_ineligible():
    candidates = classify_edit_candidates([_finding(verdict=None)])

    assert len(candidates) == 1
    c = candidates[0]
    assert c.eligible is False
    assert c.default_selected is False
    assert c.ineligible_reason == "Finding has not been verified"


def test_empty_existing_text_marked_ineligible():
    # Chunk 7: an EDIT action with empty existingText is now rejected at
    # parse time. Directly-constructed Findings that bypass the parser
    # still get rejected by ``as_edit_proposal``'s defensive validation,
    # so the candidate lands in the ineligible bucket. The previous
    # message — "Finding has no anchor text to locate in the document" —
    # was generated by the legacy fallback path that ran after the
    # proposal had already been built; the new path returns a clearer
    # "Unsupported action type" since the proposal was rejected outright
    # (the parser would have stamped a specific demotion reason).
    candidates = classify_edit_candidates([_finding(existing="  ", verdict="CONFIRMED")])

    assert len(candidates) == 1
    c = candidates[0]
    assert c.eligible is False
    assert c.default_selected is False
    assert c.ineligible_reason is not None
    assert "EDIT" in c.ineligible_reason


def test_mixed_findings_counts_and_ordering_with_cross_check():
    main = [
        _finding(verdict="CONFIRMED"),
        _finding(action="ADD", verdict="CONFIRMED"),
        _finding(verdict="UNVERIFIED"),
    ]
    cross = [
        _finding(verdict="DISPUTED"),
        _finding(verdict="CORRECTED", correction="fixed"),
    ]

    candidates = classify_edit_candidates(main, cross_check_findings=cross, include_cross_check=True)

    assert len(candidates) == 5
    assert [c.verdict_badge for c in candidates] == ["CONFIRMED", "CONFIRMED", "UNVERIFIED", "DISPUTED", "CORRECTED"]
    assert [c.finding_index for c in candidates] == [0, 1, 2, 3, 4]
    assert [c.eligible for c in candidates] == [True, True, True, False, True]
    assert candidates[3].ineligible_reason == "Finding was disputed by the verifier"
