"""Code-execution container continuity across ``pause_turn`` resumes.

``web_search_20260209`` / ``web_fetch_20260209`` default their
``allowed_callers`` to ``["code_execution_20260120"]`` — dynamic filtering
runs the search from inside a code-execution container that the API
provisions automatically (both web tools share one). That container is
invisible until a turn PAUSES mid-filter: the paused assistant content then
carries tool uses generated by code execution that have not completed, and a
continuation that does not name the container is rejected outright:

    HTTP 400 invalid_request_error: container_id is required when there are
    pending tool uses generated by code execution with tools.

This is not a degradation — an unnamed container makes the resume
*unissuable*, so every token the paused turn already spent is lost. It was
observed in production killing two of four research dimensions on a single
run, each after ~20 searches and a full minute of billed work.

There are exactly three ``pause_turn`` resume sites, and all three are
covered below because a site that forgets the container does not fail
gracefully:

1. the research fan-out loop (``requirements_research``),
2. the real-time verifier loop (``verifier._run_verification_call``),
3. the batch continuation builder (``verifier`` wave loop →
   ``verification_routing.build_verification_request``).

**The negative case is load-bearing too.** A conversation that never
provisioned a container must send no ``container`` key at all, so initial
requests — and every request under a tool configuration that does not use
code execution — keep a byte-identical body. `TestNoContainerKeepsBodyIdentical`
is what stops the fix from becoming a silent request-shape change.

The request contract is a top-level ``container`` parameter holding the
**bare string id** (the ``{"id": ...}`` object shape is what the *response*
carries, not what the request takes); a container is checkpointed after ~5
minutes of inactivity and restored by any request naming it inside the
30-day expiry window, which is why this is safe across the long gaps between
batch verification waves and not only inside tight real-time loops.
"""
from __future__ import annotations

import dataclasses
from types import SimpleNamespace

import pytest

import src.verification.verifier as V
from src.batch.batch import BatchJob
from src.core.api_config import (
    apply_container_config,
    container_id_from_response,
)
from src.core.code_cycles import DEFAULT_CYCLE
from src.core.project_profile import ProjectProfile
from src.modules import DEFAULT_MODULE
from src.research.requirements_research import (
    ResearchDimension,
    run_requirements_research,
)
from src.review.reviewer import Finding
from src.verification.verification_routing import (
    build_verification_request,
    select_routing,
)
from tests.fixtures.fake_anthropic import (
    FakeContainer,
    FakeMessage,
    batch_verification_result,
    pause_turn_response,
    research_tool_use_response,
    verification_tool_use_response,
)

CONTAINER_ID = "container_01AbCdEfGhIjKlMnOpQrSt"
SECOND_CONTAINER_ID = "container_02ZyXwVuTsRqPoNmLkJiHg"
SEARCHED_URL = "https://codes.example.gov/adoption"


# ---------------------------------------------------------------------------
# Shared fakes
# ---------------------------------------------------------------------------


class _FakeStream:
    def __init__(self, message):
        self._message = message

    def __enter__(self):
        return self

    def __exit__(self, *args):
        return False

    def get_final_message(self):
        return self._message


class _FakeMessagesAPI:
    def __init__(self, route):
        self._route = route
        self.calls: list[dict] = []

    def stream(self, **kwargs):
        self.calls.append(kwargs)
        result = self._route(kwargs)
        if isinstance(result, Exception):
            raise result
        return _FakeStream(result)


class _FakeClient:
    def __init__(self, route):
        self.messages = _FakeMessagesAPI(route)

    @property
    def calls(self) -> list[dict]:
        return self.messages.calls


def _sequential(responses: list):
    """Route successive calls through ``responses`` in order."""
    remaining = list(responses)

    def route(_kwargs):
        assert remaining, "fake client ran out of scripted responses"
        return remaining.pop(0)

    return route


def _with_container(message, container_id: str | None):
    """Return ``message`` carrying (or not carrying) a container object."""
    return dataclasses.replace(
        message,
        container=FakeContainer(id=container_id) if container_id else None,
    )


def _finding() -> Finding:
    return Finding(
        severity="HIGH",
        fileName="21 10 00 - Water-Based Fire Protection.docx",
        section="2.1",
        issue="Cited sprinkler standard edition may not match local adoption.",
        actionType="REPORT_ONLY",
        existingText=None,
        replacementText=None,
        codeReference="NFPA 13",
        confidence=0.7,
    )


# ---------------------------------------------------------------------------
# 1. The helpers
# ---------------------------------------------------------------------------


class TestContainerHelpers:
    def test_reads_id_from_an_sdk_style_response(self):
        response = FakeMessage(content=[], container=FakeContainer(id=CONTAINER_ID))
        assert container_id_from_response(response) == CONTAINER_ID

    def test_reads_id_from_a_plain_dict_response(self):
        assert (
            container_id_from_response({"container": {"id": CONTAINER_ID}})
            == CONTAINER_ID
        )

    def test_accepts_an_already_bare_id(self):
        """A caller round-tripping its own request value must not lose it."""
        assert container_id_from_response({"container": CONTAINER_ID}) == CONTAINER_ID

    @pytest.mark.parametrize(
        "response",
        [
            FakeMessage(content=[]),                      # no code execution ran
            {"container": None},                          # explicit null
            {"container": {}},                            # object without an id
            {"container": {"id": ""}},                    # empty id
            {},                                           # no key at all
            SimpleNamespace(),                            # legacy / mocked object
        ],
    )
    def test_returns_none_when_no_usable_id_is_present(self, response):
        assert container_id_from_response(response) is None

    def test_never_raises_on_a_hostile_response(self):
        """Reading transport metadata must not sink the call it enables."""

        class Exploding:
            @property
            def container(self):
                raise RuntimeError("boom")

        assert container_id_from_response(Exploding()) is None

    def test_apply_writes_the_bare_string_not_the_response_wrapper(self):
        """The request parameter is the id itself; ``{"id": ...}`` is a 400."""
        params: dict = {}
        apply_container_config(params, CONTAINER_ID)
        assert params == {"container": CONTAINER_ID}

    @pytest.mark.parametrize("empty", [None, ""])
    def test_apply_is_a_no_op_without_an_id(self, empty):
        params = {"model": "claude-sonnet-5"}
        apply_container_config(params, empty)
        assert params == {"model": "claude-sonnet-5"}
        assert "container" not in params


# ---------------------------------------------------------------------------
# 2. Research fan-out loop
# ---------------------------------------------------------------------------


def _dimension(dimension_id: str = "alpha", **overrides) -> ResearchDimension:
    return ResearchDimension(
        dimension_id=dimension_id,
        title=dimension_id.title(),
        prompt_template=(
            f"{dimension_id.upper()} research brief for "
            "{city}, {state_or_province}."
        ),
        **overrides,
    )


def _enabled_module(**overrides):
    defaults = dict(
        project_profile_enabled=True,
        research_persona="You are a test research assistant.",
        research_dimensions=(_dimension(),),
        compliance_persona="You are a test compliance reviewer.",
        compliance_severity_definitions="- CRITICAL — permit-blocking omission.",
    )
    defaults.update(overrides)
    return dataclasses.replace(DEFAULT_MODULE, **defaults)


def _profile() -> ProjectProfile:
    return ProjectProfile(
        city="Markham",
        state_or_province="ON",
        country="Canada",
        client_name="ExampleCo",
    )


def _research_payload() -> dict:
    return {
        "items": [
            {
                "topic": "Local adoption",
                "category": "ahj_requirement",
                "requirement": "Requirement grounded by the pre-pause search.",
                "actionability": "spec_requirement",
                "authority": None,
                "code_reference": None,
                "source_urls": [SEARCHED_URL],
                "confidence": 0.8,
                "qualifications": None,
            }
        ]
    }


def _run_research(responses: list):
    client = _FakeClient(_sequential(responses))
    profile = run_requirements_research(
        _enabled_module(), _profile(), client=client
    )
    return profile, client


class TestResearchContinuationCarriesContainer:
    def test_resume_after_a_pause_names_the_container(self):
        """The regression that lost two production research dimensions."""
        paused = _with_container(
            pause_turn_response(searched_urls=[SEARCHED_URL]), CONTAINER_ID
        )
        done = _with_container(
            research_tool_use_response(
                payload=_research_payload(), searched_urls=[SEARCHED_URL]
            ),
            CONTAINER_ID,
        )
        _profile_out, client = _run_research([paused, done])

        assert len(client.calls) == 2, "expected one initial call and one resume"
        assert "container" not in client.calls[0], "initial call provisions the container"
        assert client.calls[1]["container"] == CONTAINER_ID

    def test_container_survives_a_turn_that_reports_none(self):
        """A turn that ran no code execution reports no container — but the
        conversation still belongs to the one an earlier turn created, so the
        id must be carried forward rather than dropped."""
        first = _with_container(
            pause_turn_response(searched_urls=[SEARCHED_URL]), CONTAINER_ID
        )
        second = _with_container(pause_turn_response(), None)
        done = _with_container(
            research_tool_use_response(
                payload=_research_payload(), searched_urls=[SEARCHED_URL]
            ),
            None,
        )
        _profile_out, client = _run_research([first, second, done])

        assert len(client.calls) == 3
        assert client.calls[1]["container"] == CONTAINER_ID
        assert client.calls[2]["container"] == CONTAINER_ID

    def test_a_newer_container_id_supersedes_the_earlier_one(self):
        first = _with_container(
            pause_turn_response(searched_urls=[SEARCHED_URL]), CONTAINER_ID
        )
        second = _with_container(pause_turn_response(), SECOND_CONTAINER_ID)
        done = _with_container(
            research_tool_use_response(
                payload=_research_payload(), searched_urls=[SEARCHED_URL]
            ),
            None,
        )
        _profile_out, client = _run_research([first, second, done])

        assert client.calls[1]["container"] == CONTAINER_ID
        assert client.calls[2]["container"] == SECOND_CONTAINER_ID


# ---------------------------------------------------------------------------
# 3. Real-time verifier loop
# ---------------------------------------------------------------------------


def _run_realtime(monkeypatch, responses: list):
    client = _FakeClient(_sequential(responses))
    monkeypatch.setattr(V, "_get_client", lambda **_: client)
    result = V.verify_finding(
        _finding(), max_retries=0, cycle=DEFAULT_CYCLE, cache=None
    )
    return result, client


def _verdict_message(container_id: str | None = None):
    """A terminal, grounded verdict response, optionally carrying a container."""
    return _with_container(
        verification_tool_use_response(),
        container_id,
    )


class TestRealtimeVerifierContinuationCarriesContainer:
    def test_resume_after_a_pause_names_the_container(self, monkeypatch):
        paused = _with_container(
            pause_turn_response(searched_urls=[SEARCHED_URL]), CONTAINER_ID
        )
        _result, client = _run_realtime(
            monkeypatch, [paused, _verdict_message(CONTAINER_ID)]
        )

        assert len(client.calls) == 2
        assert "container" not in client.calls[0]
        assert client.calls[1]["container"] == CONTAINER_ID

    def test_container_survives_a_turn_that_reports_none(self, monkeypatch):
        first = _with_container(
            pause_turn_response(searched_urls=[SEARCHED_URL]), CONTAINER_ID
        )
        second = _with_container(pause_turn_response(), None)
        _result, client = _run_realtime(
            monkeypatch, [first, second, _verdict_message(None)]
        )

        assert len(client.calls) == 3
        assert client.calls[1]["container"] == CONTAINER_ID
        assert client.calls[2]["container"] == CONTAINER_ID


# ---------------------------------------------------------------------------
# 4. Batch continuation
# ---------------------------------------------------------------------------


def _classify(monkeypatch, contexts: dict, message):
    job = BatchJob(
        batch_id="container-test",
        job_type="verify",
        request_map={cid: {"model": "claude-sonnet-5"} for cid in contexts},
        created_at=0.0,
    )
    monkeypatch.setattr(
        V,
        "retrieve_verification_results_detailed",
        lambda _job: {
            cid: batch_verification_result(cid, message=message) for cid in contexts
        },
    )
    outcomes = V._classify_wave_results(
        job=job, findings=[_finding()], request_contexts=contexts
    )
    assert len(outcomes) == 1
    return outcomes[0]


class TestBatchContinuationCarriesContainer:
    def test_pause_outcome_records_the_container_id(self, monkeypatch):
        outcome = _classify(
            monkeypatch,
            {"verify__0": {"finding_idx": 0, "model": "claude-sonnet-5"}},
            _with_container(
                pause_turn_response(searched_urls=[SEARCHED_URL]), CONTAINER_ID
            ),
        )
        assert outcome.classification == "continue"
        assert outcome.container_id == CONTAINER_ID

    def test_prior_container_id_is_carried_when_a_wave_reports_none(
        self, monkeypatch
    ):
        """Wave N+2 must resume into the container wave N created."""
        outcome = _classify(
            monkeypatch,
            {
                "verify_cont_1__verify__0": {
                    "finding_idx": 0,
                    "model": "claude-sonnet-5",
                    "prior_container_id": CONTAINER_ID,
                }
            },
            _with_container(pause_turn_response(), None),
        )
        assert outcome.container_id == CONTAINER_ID

    def test_continuation_request_body_carries_the_container(self):
        request = V._build_continuation_request(
            "original prompt",
            [{"type": "text", "text": "prior turn"}],
            cycle=DEFAULT_CYCLE,
            model="claude-sonnet-5",
            severity="HIGH",
            finding=_finding(),
            container_id=CONTAINER_ID,
        )
        assert request.params["container"] == CONTAINER_ID

    def test_container_is_a_body_field_not_a_transport_header(self):
        """It must ride ``params`` so the batch API's per-item body carries it;
        ``extra_headers`` is the SDK transport seam and the batch API rejects
        unknown body keys, so getting this backwards fails in opposite ways on
        the two transports."""
        request = V._build_continuation_request(
            "original prompt",
            [{"type": "text", "text": "prior turn"}],
            cycle=DEFAULT_CYCLE,
            model="claude-sonnet-5",
            severity="HIGH",
            finding=_finding(),
            container_id=CONTAINER_ID,
        )
        assert "container" not in (request.extra_headers or {})
        assert "container" in request.params


# ---------------------------------------------------------------------------
# 5. The negative case: no container ⇒ byte-identical body
# ---------------------------------------------------------------------------


class TestNoContainerKeepsBodyIdentical:
    def test_initial_verification_request_has_no_container_key(self):
        decision = select_routing(
            _finding(), escalated=False, local_skip=False, cycle=DEFAULT_CYCLE
        )
        request = build_verification_request(
            decision, prompt="p", system_prompt="s"
        )
        assert "container" not in request.params

    def test_continuation_without_an_id_has_no_container_key(self):
        request = V._build_continuation_request(
            "original prompt",
            [{"type": "text", "text": "prior turn"}],
            cycle=DEFAULT_CYCLE,
            model="claude-sonnet-5",
            severity="HIGH",
            finding=_finding(),
            container_id=None,
        )
        assert "container" not in request.params

    def test_research_conversation_without_containers_sends_no_key(self):
        paused = _with_container(
            pause_turn_response(searched_urls=[SEARCHED_URL]), None
        )
        done = _with_container(
            research_tool_use_response(
                payload=_research_payload(), searched_urls=[SEARCHED_URL]
            ),
            None,
        )
        _profile_out, client = _run_research([paused, done])
        assert all("container" not in call for call in client.calls)

    def test_realtime_conversation_without_containers_sends_no_key(
        self, monkeypatch
    ):
        paused = _with_container(
            pause_turn_response(searched_urls=[SEARCHED_URL]), None
        )
        _result, client = _run_realtime(
            monkeypatch, [paused, _verdict_message(None)]
        )
        assert all("container" not in call for call in client.calls)
