"""Shared configuration for verification API calls."""

VERIFICATION_MODEL = "claude-opus-4-6"
VERIFICATION_MAX_TOKENS = 128_000

WEB_SEARCH_TOOL = {
    "type": "web_search_20250305",
    "name": "web_search",
    "blocked_domains": [
        "reddit.com",
        "quora.com",
        "medium.com",
        "chatgpt.com",
        "perplexity.ai",
        "openai.com",
        "gemini.google.com",
        "claude.ai",
        "you.com",
        "phind.com",
        "copilot.microsoft.com",
        "poe.com",
        "character.ai",
        "jasper.ai", 
        "writesonic.com",
        "stackexchange.com",   # engineering.stackexchange is not authoritative for CA codes
        "stackoverflow.com",   # software, not building codes
        "answers.yahoo.com",
        "fixya.com",
        "diychatroom.com",
        "forums.jlconline.com",
        "hvac-talk.com",       # contractor forum, not code authority
        "inspectionnews.net",
        "inspectorsforum.com",
        "contractortalk.com",
        "doityourself.com",
        "homeadvisor.com",
        "thumbtack.com",
        "angi.com",
        "ehow.com",
        "wikihow.com",
        "about.com",
        "thespruce.com",
        "bobvila.com",
        "familyhandyman.com",
        "hunker.com",
        "sapling.com",
        "reference.com",
        "leaf.tv",
        "sciencing.com",
        "bizfluent.com",
        "pocketsense.com",
        "facebook.com",
        "twitter.com",
        "x.com",
        "instagram.com",
        "tiktok.com",
        "linkedin.com",
        "pinterest.com",
        "youtube.com",          # can't parse video content anyway
        "threads.net",
        "wikipedia.org",
        "britannica.com",
        "simple.wikipedia.org",
    ],
    "max_uses": 10,
    "user_location": {
        "type": "approximate",
        "country": "US",
        "region": "California",
    },
}